version: "3.9"

services:
  db:
    image: postgres:13
    container_name: python-app-db-1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: python-app-web-1
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    container_name: python-app-prometheus-1
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9091:9090"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: python-app-node-exporter-1
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana:latest
    container_name: python-app-grafana-1
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  db_data:
  grafana_data:

